# Generated by Django 6.1.1 on 2026-09-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
